### ISSUE TITLE
Update for compatibility with Red 3.5

### ISSUE THREAD

**Issue by DanasaurUK** [AXVin/AXVin-Cogs#10]
Please could the code be updated to work with Red's new V3.5?

**Comment by AXVin** [comment]
@DanasaurUK Can you let me know which cog doesn't work and the errors you get. I am not really acquainted with the changelogs of Red v3 so such information will help me to look things up efficiently

**Comment by DanasaurUK** [comment]
The error I get is:
```python
Exception during loading of package
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1686, in load_extension
    await lib.setup(self)
TypeError: object NoneType can't be used in 'await' expression
