### ISSUE TITLE
I've now got a new error

### ISSUE THREAD

**Issue by DanasaurUK** [AXVin/AXVin-Cogs#6]
I've now got a new error

```
Unhandled exception in internal background task 'update_channels'.
Traceback (most recent call last):
  File "c:\users\dan\moasesbot-env\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\Dan\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\MoasesBot\cogs\CogManager\cogs\clock\clock.py", line 61, in update_channels
    time = time.strftime(fmt)
ValueError: Invalid format string
Unhandled exception in internal background task 'update_channels'.
Traceback (most recent call last):
  File "c:\users\dan\moasesbot-env\lib\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\Dan\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\MoasesBot\cogs\CogManager\cogs\clock\clock.py", line 61, in update_channels
    time = time.strftime(fmt)
ValueError: Invalid format string
```

_Originally posted by @DanasaurUK in https://github.com/AXVin/AXVin-Cogs/issues/5#issuecomment-869063254_

**Comment by AXVin** [comment]
Thanks again for reporting! This issue should be fixed. Please update the cog
