### ISSUE TITLE
Watch2Gether API error

### ISSUE THREAD

**Issue by one-juru** [AXVin/AXVin-Cogs#8]
I run Red in a docker container, and wanted to install the watch2gether cog, since I really like the idea. I entered the api key, but every time I run the command I get this error. It seems that he can't read the streamkey, or that watch2gether doesn't even return one. Here is the error log. Do you have any idea? Thank you for your time.

```
[2022-01-28 14:38:41] [ERROR] red: Exception in command 'watch2gether'
Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/data/extra-cogs/AXVin-Cogs/watch2gether/watch2gether.py", line 121, in watch2gether
    room_key = jsondata["streamkey"]
KeyError: 'streamkey'```

**Comment by AXVin** [comment]
Hey, this was a cause of an API change.
I just updated the code and it should be working with the new changes. Please try it!

**Comment by one-juru** [comment]
Sorry for the late reply and thank you, the update fixed it :)
